-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
/*--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------*/
TEAM_AOD = DarkRP.createJob("Wybieranie strony", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/police.mdl"},
   description = [[Wybierz swoja prace!]],
   weapons = {},
   command = "aod",
   max = 0,
   salary = 0,
   admin = 1,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Administration",
})

TEAM_AOD = DarkRP.createJob("Developer", {
   color = Color(255, 255, 0, 255),
   model = {"models/player/combine_super_soldier.mdl"},
   description = [[Klasa rozwijana do użytku wyłącznie przez programistów.]],
   weapons = {},
   command = "dev",
   max = 0,
   salary = 0,
   admin = 1,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Administration",
   customCheck = function(ply) return ply:SteamID() == "STEAM_0:0:53440724" end,
})

TEAM_SCAVENGER = AddExtraTeam("Scavenger", {
    color = Color(20, 150, 20, 255),
    model = "models/player/arctic.mdl",
    description = [[Wyjdź i przeszukaj bazy Cilian i zabierz ich rzeczy.]],
    weapons = {"weapon_fists", "lockpick", "keypad_cracker"},
    command = "scavenger",
    max = 5,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_RAIDER = AddExtraTeam("Raider", {
   color = Color(20, 150, 20, 255),
    model = "models/player/legion/3e_soldier.mdl",
    description = [[Zaawansowany śmieciarz.]],
    weapons = {"weapon_fists", "lockpick", "keypad_cracker", "m9k_colt1911"},
    command = "raider",
    max = 2,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians",
     customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_RAIDER = AddExtraTeam("Abductor", {
   color = Color(20, 150, 20, 255),
    model = "models/player/phoenix.mdl",
    description = [[Porywacze porywają (porywają) ludzi i trzymają ich za okup. Maksymalny okup to 100 000 $.]],
    weapons = {"weapon_cuff_elastic", "m9k_spas12"},
    command = "abductor",
    max = 1,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_LGUN = AddExtraTeam("Light Arms Dealer", {
    color = Color(20, 150, 20, 255),
    model = "models/player/pmc_3/pmc__01.mdl",
    description = [[Neutralna partia wszystkich wojen. Dostarcza broń żołnierzom.]],
    weapons = {"m9k_spas12", "m9k_usas", "m9k_mossberg590", "m9k_model627", "m9k_coltpython", "m9k_mp5sd", "m9k_aw50", "m9k_magpulpdr", "m9k_svu", "m9k_ares_shrike", "m9k_fg42", "m9k_acr"},
    command = "lightarmsdealer",
    max = 2,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_US1 = DarkRP.createJob("US Rekrut", {
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2h.mdl"},
   description = [[Jesteś jednostką piechoty dla armii Stanów Zjednoczonych. Postępuj zgodnie z poleceniami przełożonego i poprowadź USA do zwycięstwa!]],
   weapons = {"m9k_acr", "m9k_deagle"},
   command = "usinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "United States",
})

TEAM_US2 = DarkRP.createJob("US Recon Unit", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/pmc_2/pmc__03.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla armii Stanów Zjednoczonych. Twoim zadaniem jest zebranie informacji o jednostkach wroga]],
   weapons = {"m9k_deagle", "m9k_m416"},
   command = "usrecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US3 = DarkRP.createJob("US Heavy Infantry", {
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla armii Stanów Zjednoczonych. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"m9k_m249lmg", "m9k_scoped_taurus"},
   command = "usheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US4 = DarkRP.createJob("US Sniper", {
   color = Color(0, 128, 255, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem dla armii Stanów Zjednoczonych. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką zwiadowczą, aby uzyskać maksymalną biegłość!]],
   weapons = {"m9k_aw50", "weapon_vj_smg1"},
   command = "ussniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US5 = DarkRP.createJob("US Support Unit", {
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2.mdl"},
   description = [[Jesteś jednostką wsparcia dla armii Stanów Zjednoczonych! Połóżcie osłonę ognia i stłumcie wroga!]],
   weapons = {"m9k_m16a4_acog", "m9k_deagle"},
   command = "ussupportunit",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US6 = DarkRP.createJob("US Medic", {
   color = Color(0, 128, 255, 255),
   model = {"models/mw2guy/bz/tfbz02.mdl"},
   description = [[Jesteś medykiem dla armii Stanów Zjednoczonych. Twoim zadaniem jest uleczyć swój zespół i utrzymać ich przy życiu!]],
   weapons = {"m9k_knife", "v92_hl2_medkit"},
   command = "usmedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US7 = DarkRP.createJob("US Officer", {
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/t_codm.mdl"},
   description = [[Jesteś oficerem armii Stanów Zjednoczonych. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony i innych działań. Przyjmujesz rozkazy od dowódcy.]],
   weapons = {"m9k_thompson", "m9k_model627"},
   command = "usofficer",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US8 = DarkRP.createJob("US Commander", {
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2he.mdl"},
   description = [[Jesteś dowódcą armii Stanów Zjednoczonych. Przyjmij rozkazy od generała armii i dowodź swoimi żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"m9k_scar", "m9k_sig_p229r"},
   command = "uscommander",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US9 = DarkRP.createJob("US General of the Army", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/pmc_2/pmc__01.mdl"},
   description = [[Jesteś generałem armii Stanów Zjednoczonych. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co masz robić, a pułkownik sprawdzi.]],
   weapons = {"m9k_an94", "m9k_glock"},
   command = "usgota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
   customCheck = function(ply) return CLIENT or
        table.HasValue({"STEAM_0:1:174545413"}, ply:SteamID())
    end,
    CustomCheckFailMsg = "Tylko Kamo może być generałem",
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "The U.S General of the Army has been killed!")
      else
         DarkRP.notifyAll(0, 4, "The U.S General of the Army has died!")
      end
   end
})                                                                                                                   

TEAM_US10 = DarkRP.createJob("US Special Forces", {
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2m.mdl"},
   description = [[Jesteś „drużyną” jednoosobowych sił specjalnych. Przyjmujesz rozkazy bezpośrednio od generała armii.]],
   weapons = {"m9k_matador", "m9k_deagle"},
   command = "usspecialforces",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

/*
TEAM_RU1 = DarkRP.createJob("RU Infantry", {
   level = 5,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_a.mdl"},
   description = [[Jesteś jednostką piechoty dla armii rosyjskiej. Postępuj zgodnie z rozkazami przełożonego i poprowadź Rosję do zwycięstwa!]],
   weapons = {"m9k_ak74", "m9k_hk45"},
   command = "ruinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU2 = DarkRP.createJob("RU Recon Unit", {
   level = 1,
   color = Color(228, 0, 0, 255),
   model = {"models/player/pmc_5/pmc__03.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla rosyjskiej armii. Twoim zadaniem jest zebranie informacji o jednostkach wroga.]],
   weapons = {"util_binoculars", "m9k_hk45"},
   command = "rurecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU3 = DarkRP.createJob("RU Heavy Infantry", {
   level = 20,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/riot/riot_ru.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla rosyjskiej armii. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"m9k_remington870", "m9k_hk45", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "ruheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU4 = DarkRP.createJob("RU Sniper", {
   level = 30,
   color = Color(228, 0, 0, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem dla armii rosyjskiej. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"m9k_dragunov", "m9k_hk45"},
   command = "rusniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU5 = DarkRP.createJob("RU Light Machine Gunner", {
   level = 50,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/riot/riot_ru.mdl"},
   description = [[Jesteś lekkim strzelcem dla armii rosyjskiej. Twoim zadaniem jest obrona bazy. NIE DOŁĄCZAJ DO RAIDÓW. JESTEŚ JEDNOSTKĄ OBRONNĄ, A NIE JEDNOSTKĄ OBRONNĄ!]],
   weapons = {"m9k_pkm", "m9k_hk45"},
   command = "rulightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU6 = DarkRP.createJob("RU Medic", {
   level = 15,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_d.mdl"},
   description = [[Jesteś medykiem dla rosyjskiej armii. Twoim zadaniem jest uleczyć swój zespół i utrzymać ich przy życiu!]],
   weapons = {"weapon_medkit", "m9k_an94", "m9k_hk45"},
   command = "rumedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU7 = DarkRP.createJob("RU Lieutenant", {
   level = 50,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_c.mdl"},
   description = [[Jesteś porucznikiem armii rosyjskiej. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony, itp. Przyjmujesz rozkazy od pułkownika.]],
   weapons = {"m9k_amd65", "m9k_hk45"},
   command = "rulieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU8 = DarkRP.createJob("RU Colonel", {
   level = 75,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_e.mdl"},
   description = [[Jesteś pułkownikiem armii rosyjskiej. Przyjmij rozkazy od generała armii i dowodź żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"m9k_ak74", "m9k_hk45"},
   command = "rucolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU9 = DarkRP.createJob("RU General of the Army", {
   color = Color(228, 0, 0, 255),
   model = {"models/player/pmc_5/pmc__01.mdl"},
   description = [[Jesteś rosyjskim generałem armii. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co ma robić, i pułkownik sprawi, że będzie to zrobione.]],
   weapons = {},
   command = "rugota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "Rosyjski generał armii został zabity!")
      else
         DarkRP.notifyAll(0, 4, "Rosyjski generał armii zmarł!")
      end
   end
})
*/

/*
-- Master Chief = models/player/Rottweiler/mc.mdl
TEAM_NWO1 = DarkRP.createJob("NWO Infantry", {
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[Jesteś jednostką piechoty dla armii NWO. Postępuj zgodnie z rozkazami przełożonego i poprowadź Rosję do zwycięstwa!]],
   weapons = {"cw_mn23", "cw_g4p_glock17"},
   command = "nwoinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO2 = DarkRP.createJob("NWO Recon Unit", {
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla armii NWO. Twoim zadaniem jest zebranie informacji o jednostkach wroga. NIE DOPUSZCZAJ SIĘ DO WŁASNEJ BRONI!]],
   weapons = {"util_binoculars", "weapon_camo"},
   command = "nworecon",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO3 = DarkRP.createJob("NWO Heavy Infantry", {
   color = Color(0, 20, 84, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla armii NWO. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "nwoheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO4 = DarkRP.createJob("NWO Sniper", {
   color = Color(0, 20, 84, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem dla armii NWO. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"cw_g4p_awm", "cw_g4p_glock17"},
   command = "nwosniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"SteamID"}, ply:SteamID())
    end,
})

TEAM_NWO5 = DarkRP.createJob("NWO Light Machine Gunner", {
   color = Color(0, 20, 84, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[Jesteś lekkim strzelcem do armii NWO. Twoim zadaniem jest obrona bazy. NIE DOŁĄCZAJ DO RAIDÓW. JESTEŚ JEDNOSTKĄ OBRONNĄ, A NIE JEDNOSTKĄ OBRONNĄ!]],
   weapons = {"cw_240b", "cw_g4p_glock17"},
   command = "nwolightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO6 = DarkRP.createJob("NWO Medic", {
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[Jesteś medykiem dla armii NWO. Twoim zadaniem jest uleczyć swój zespół i utrzymać ich przy życiu!]],
   weapons = {"weapon_medkit", "cw_mp5", "cw_g4p_glock17"},
   command = "nwomedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO7 = DarkRP.createJob("NWO Lieutenant", {
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4pm.mdl"},
   description = [[Jesteś porucznikiem armii NWO. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony, itp. Przyjmujesz rozkazy od pułkownika.]],
   weapons = {"cw_g4p_xm8", "cw_g4p_glock17"},
   command = "nwolieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO8 = DarkRP.createJob("NWO Colonel", {
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[Jesteś pułkownikiem armii NWO. Przyjmij rozkazy od generała armii i dowodź żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"cw_g4p_magpul_masada", "cw_g4p_glock17"},
   command = "nwocolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_NWO9 = DarkRP.createJob("NWO General of the Army", {
   color = Color(0, 20, 84, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[Jesteś generałem armii NWO. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co ma robić, i pułkownik sprawi, że będzie to zrobione.]],
   weapons = {},
   command = "nwogota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "Generał NWO armii został zabity!")
      else
         DarkRP.notifyAll(0, 4, "Generał NWO armii został zabity!")
      end
   end
})

*/

-- CHINESE --
TEAM_CN1 = DarkRP.createJob("CN Infantry", {
   color = Color(255, 56, 25, 255),
   model = {
            "models/voxelzero/player/odst.mdl"
            },
   description = [[Jesteś jednostką piechoty dla chińskiej armii. Postępuj zgodnie z rozkazami przełożonego i poprowadź Rosję do zwycięstwa!]],
   weapons = {"cw_aw_ak12", "cw_g4p_glock17"},
   command = "cninfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN2 = DarkRP.createJob("CN Recon Unit", {
   color = Color(255, 56, 25, 255),
   model = {"models/mass effect 2/player/inferno_armour_colour.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla chińskiej armii. Twoim zadaniem jest zebranie informacji o jednostkach wroga. NIE DOPUSZCZAJ SIĘ DO WŁASNEJ BRONI!]],
   weapons = {"util_binoculars", "weapon_camo"},
   command = "cnrecon",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN3 = DarkRP.createJob("CN Heavy Infantry", {
   color = Color(255, 56, 25, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla chińskiej armii. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "cnheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN4 = DarkRP.createJob("CN Sniper", {
   color = Color(255, 56, 25, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem chińskiej armii. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"cw_g4p_awm", "cw_g4p_glock17"},
   command = "cnsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN5 = DarkRP.createJob("CN Support Unit", {
   color = Color(255, 56, 25, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[Jesteś jednostką wsparcia dla chińskiej armii! Połóżcie osłonę ognia i stłumcie wroga!]],
   weapons = {"cw_ak74", "cw_g4p_glock17"},
   command = "cnsupportunit",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN6 = DarkRP.createJob("CN Medic", {
   color = Color(255, 56, 25, 255),
   model = {"models/mass effect 2/player/inferno_armour_colour.mdl"},
   description = [[Jesteś medykiem dla chińskiej armii. Twoim zadaniem jest uzdrowienie zespołu i utrzymanie go przy życiu!]],
   weapons = {"weapon_medkit", "cw_mp5", "cw_g4p_glock17"},
   command = "cnmedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN7 = DarkRP.createJob("CN Officer", {
   color = Color(255, 56, 25, 255),
   model = {
            "models/voxelzero/player/voxelspartan.mdl"
            },
   description = [[Jesteś oficerem armii chińskiej. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony, itp. Przyjmujesz rozkazy od pułkownika.]],
   weapons = {"cw_mn23", "cw_g4p_glock17"},
   command = "cnofficer",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN8 = DarkRP.createJob("CN Commander", {
   color = Color(255, 56, 25, 255),
   model = {"models/voxelzero/player/voxelspartan.mdl"},
   description = [[Jesteś dowódcą armii chińskiej. Przyjmij rozkazy od generała armii i dowodź żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"cw_aacgsm", "cw_g4p_glock17"},
   command = "cncommander",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN9 = DarkRP.createJob("CN General of the Army", {
   color = Color(255, 56, 25, 255),
   model = {"models/voxelzero/player/voxelspartan.mdl"},
   description = [[Jesteś chińskim generałem armii. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co ma robić, i pułkownik sprawi, że będzie to zrobione.]],
   weapons = {},
   command = "cngota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "CN General of the Army został zabity!")
      else
         DarkRP.notifyAll(0, 4, "Zmarł generał CN armii!")
      end
   end
})

TEAM_CN10 = DarkRP.createJob("CN Special Forces", {
   color = Color(0, 128, 255, 255),
   model = {"models/voxelzero/player/voxelspartan.mdl"},
   description = [[You are  a one manned special forces "team". You take orders directly from the General of the Army.]],
   weapons = {"cw_aacgsm", "cw_g4p_g2contender", "cw_g4p_glock17"},
   command = "cnspecialforces",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CN11 = DarkRP.createJob("CN Infiltrator", {
   color = Color(0, 128, 255, 255),
   model = {"models/mass effect 2/player/inferno_armour_colour.mdl"},
   description = [[Jesteś infiltratorem chińskiej armii! Infiltruj bazy wroga i przełam ich obronę od środka!]],
   weapons = {"cw_clue_test", "cw_g4p_glock17", "realistic_hook"},
   command = "cninfiltrator",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "China",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})


-- GERMANY --

TEAM_DE1 = DarkRP.createJob("DE Rekrut", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__12.mdl"},
   description = [[Jesteś jednostką piechoty dla armii niemieckiej. Postępuj zgodnie z poleceniami przełożonego i poprowadź Niemcy do zwycięstwa!]],
   weapons = {"m9k_mp40", "cw_g4p_usp40"},
   command = "deinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Germany",
})

TEAM_DE2 = DarkRP.createJob("DE Recon Unit", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__03.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla armii niemieckiej. Twoim zadaniem jest zebranie informacji o jednostkach wroga.]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "derecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE3 = DarkRP.createJob("DE Heavy Infantry", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__14.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla armii niemieckiej. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "deheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE4 = DarkRP.createJob("DE Sniper", {
   color = Color(32, 32, 32, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem dla armii niemieckiej. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"cw_g4p_m98b", "m9k_mp40"},
   command = "desniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE5 = DarkRP.createJob("DE Support Unit", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__13.mdl"},
   description = [[Jesteś jednostką wsparcia dla armii niemieckiej! Połóżcie osłonę ognia i stłumcie wroga!]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "delightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE6 = DarkRP.createJob("DE Medic", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__02.mdl"},
   description = [[Jesteś medykiem dla armii niemieckiej. Twoim zadaniem jest uzdrowienie zespołu i utrzymanie go przy życiu!]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "demedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE7 = DarkRP.createJob("DE Officer", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__07.mdl"},
   description = [[Jesteś oficerem armii niemieckiej. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony, itp. Przyjmujesz rozkazy od pułkownika.]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "delieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE8 = DarkRP.createJob("DE Commander", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__04.mdl"},
   description = [[Jesteś dowódcą armii niemieckiej. Przyjmij rozkazy od generała armii i dowodź żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "decolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE9 = DarkRP.createJob("DE General of the Army", {
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__01.mdl"},
   description = [[Jesteś niemieckim generałem armii. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co ma robić, i pułkownik sprawi, że będzie to zrobione.]],
   weapons = {"m9k_mp40", "m9k_tec9"},
   command = "degota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "Niemiecki generał armii został zabity!")
      else
         DarkRP.notifyAll(0, 4, "Niemiecki generał armii zmarł!")
      end
   end
})

TEAM_DE10 = DarkRP.createJob("DE Special Forces", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/pmc_4/pmc__04.mdl"},
   description = [[Jesteś jednoosobową „drużyną” sił specjalnych. Przyjmujesz rozkazy bezpośrednio od generała armii.]],
   weapons = {"m9k_mp40", "m9k_tec9", "cw_g4p_usp40"},
   command = "despecialforces",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE11 = DarkRP.createJob("DE Infiltrator", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/pmc_4/pmc__03.mdl"},
   description = [[Jesteś infiltratorem niemieckiej armii! Infiltruj bazy wroga i przełam ich obronę od wewnątrz!]],
   weapons = {"m9k_mp40", "m9k_tec9", "realistic_hook"},
   command = "deinfiltrator",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "Germany",
})


-- CELL --

TEAM_XOF1 = DarkRP.createJob("XOF Soldier", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_xof.mdl"},
   description = [[Jesteś żołnierzem dla PMC. Śledź swoje zamówienia i zarabiaj.]],
   weapons = {"cw_g4p_glock17", "cw_kk_hk416"},
   command = "xofinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF2 = DarkRP.createJob("XOF Heavy Soldier", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_xof2.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla Kompanii Wojskowej XOF. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick", "keypad_cracker"},
   command = "Odwołaj licencję na broń",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF3 = DarkRP.createJob("XOF Recon Unit", {
   color = Color(107, 101, 43, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla XOF Military Company. Twoim zadaniem jest zebranie informacji o jednostkach wroga]],
   weapons = {"cw_g4p_glock17", "util_binoculars"},
   command = "xofreconunit",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF4 = DarkRP.createJob("XOF Medic", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_xof.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla XOF Military Company. Twoim zadaniem jest zebranie informacji o jednostkach wroga]],
   weapons = {"weapon_medkit", "m9k_vector", "cw_g4p_glock17"}, 
   command = "xofmedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF5 = DarkRP.createJob("XOF Commander", {
   color = Color(107, 101, 43, 255),
   model = {"models/player/mgs4_bigboss.mdl"},
   description = [[Jesteś dowódcą kompanii wojskowej XOF. Dowodzić swoimi żołnierzami i przyjmować lub odrzucać prośby o zatrudnienie.]],
   weapons = {},
   command = "xofcommander",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF6 = DarkRP.createJob("XOF Juggernaut", {
   color = Color(107, 101, 43, 255),
   model = {"models/mw2guy/riot/juggernaut.mdl"},
   description = [[Jesteś dowódcą kompanii wojskowej XOF. Dowodzić swoimi żołnierzami i przyjmować lub odrzucać prośby o zatrudnienie..]],
   weapons = {"cw_240b", "cw_g4p_ump45", "cw_deagle"},
   command = "xofjuggernaut",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "XOF Military Company",
   PlayerSpawn =  function(ply) ply:SetArmor(200) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF7 = DarkRP.createJob("XOF Officer", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_xof2.mdl"},
   description = [[Jesteś oficerem XOF Military Company. Poprowadź swoich żołnierzy na polu i upewnij się, że nie zawiedziesz swojego klienta.]],
   weapons = {"cw_g4p_magpul_masada", "cw_g4p_glock17"},
   command = "xofofficer",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF8 = DarkRP.createJob("XOF Special Forces", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs4_haven_trooper.mdl"},
   description = [[Jesteście siłami specjalnymi dla XOF Military Company. Nie współpracujesz z innymi częściami firmy. Pracujesz solo lub z innymi siłami specjalnymi w firmie]],
   weapons = {"cw_mn23", "cw_g4p_awm", "cw_g4p_glock17"},
   command = "xofspecialforces",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF9 = DarkRP.createJob("XOF Sniper", {
   color = Color(107, 101, 43, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś legendarnym snajperem dla XOF Military Company, Quiet. Postępuj zgodnie z poleceniami oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną wydajność!]],
   weapons = {"cw_g4p_awm", "cw_g4p_glock17"},
   command = "xofsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF10 = DarkRP.createJob("XOF Assassin", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs4_haven_trooper.mdl"},
   description = [[Jesteś zabójcą dla XOF. Zabijaj ludzi dla pieniędzy. To takie proste.]],
   weapons = {"cw_g4p_glock17", "util_binoculars"},
   command = "xofassassin",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF11 = DarkRP.createJob("XOF Protection Unit", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_xof.mdl"},
   description = [[Jesteś jednostką ochronną dla firmy wojskowej XOF. Ludzie płacą za ochronę tego, co chcą chronić.]],
   weapons = {"cw_g4p_glock17", "cw_aacgsm"},
   command = "xofprotectionunit",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF12 = DarkRP.createJob("XOF Sabatoge Specialist", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_xof.mdl"},
   description = [[Jesteś specjalistą od sabatoge dla firmy wojskowej XOF. Zniszcz rzeczy za pieniądze. TO NIE JEST KLASA Bomberów samobójczych! KAŻDY NIEWINNY LUDZIE, KTÓRE UMIERAJĄ Z WYBUCHU MOGĄ BYĆ UWAŻANE!]],
   weapons = {"cw_g4p_glock17", "cw_xm1014", "m9k_suicide_bomb"},
   command = "xofsabatogespecialist",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_XOF13 = DarkRP.createJob("XOF Elite Commando", {
   color = Color(107, 101, 43, 255),
   model = {"models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit.mdl",
            "models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit_bandana.mdl",
            "models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit_bloody.mdl",
            "models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit_bloody_bandana.mdl",
            "models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit_wet.mdl",
            "models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit_wet_bandana.mdl",
            "models/ninja/mgs5gz/mgs5_gz_big_boss_sneaking_suit.mdl",
            "models/ninja/mgs5gz/mgs5_gz_msf_sneaking_suit.mdl"
            },
   description = [[Jesteś XOF Elite Commando. Prowadzisz naloty w dowolnym miejscu ... Za odpowiednią cenę. Nikomu nie odpowiadasz i wykonujesz swoje misje według własnego uznania. Jesteś uważany za najbardziej elitarnego żołnierza, nie tylko w XOF, ale na całym polu bitwy. Powinieneś się bać.]],
   weapons = {"cw_kk_hk416", "cw_g4p_customizable_knife", "cw_deagle", "cw_g4p_g2contender", "cw_xm1014"},
   command = "xofelitecommando",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "XOF Military Company",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end
})

/*
TEAM_T1 = DarkRP.createJob("Terrorist", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_grunt.mdl"},
   description = [[Jesteś standardowym terrorystą. Przyjmij rozkazy od swojego lidera. PAMIĘTAJ, ŻE TYLKO 30 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {},
   command = "terrorist",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "Terrorists",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_T2 = DarkRP.createJob("Terrorist Leader", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_rpg.mdl"},
   description = [[Jesteś przywódcą terrorystów. Poinformuj innych terrorystów o swoich planach na maksymalny chaos! PAMIĘTAJ, ŻE TYLKO 30 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {},
   command = "terroristleader",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Terrorists",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end
})

TEAM_T3 = DarkRP.createJob("Suicide Bomber", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_bomber.mdl"},
   description = [[Jesteś zamachowcem-samobójcą! Wysadź się w powietrze, aby wywołać chaos! PAMIĘTAJ, ŻE TYLKO 15 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {"m9k_suicide_bomb"},
   command = "suicidebomber",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 3,
   category = "Terrorists",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end
})
*/

TEAM_A1 = DarkRP.createJob("Anarchist", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/bobert/aodeadshot.mdl"},
   description = [[Jesteś zwykłym anarchistą. Przyjmij rozkazy od swojego przywódcy Anarchii i zlikwiduj wszystkie formy rządów!]],
   weapons = {},
   command = "anarchist",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "Anarchists",
   customCheck = function(ply)
        return ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_A2 = DarkRP.createJob("Anarchy", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/bobert/aoa.mdl"},
   description = [[Jesteś liderem anarchistów. Powiedz innym anarchistom, że planujesz obalić wszystkie formy rządzenia!]],
   weapons = {},
   command = "anarchy",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Anarchists",
   customCheck = function(ply)
        return ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

/*
TEAM_A3 = DarkRP.createJob("Anarchist Bomber", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_bomber.mdl"},
   description = [[Jesteś zamachowcem-samobójcą! Wysadź się w powietrze, aby wywołać chaos! PAMIĘTAJ, ŻE TYLKO 15 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {"m9k_suicide_bomb"},
   command = "anarchistbomber",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 3,
   category = "Anarchists ",
   customCheck = function(ply)
        return ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})
*/

TEAM_MP1 = DarkRP.createJob("MP Soldier", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[Jesteście piechotą dla Organizacji Narodów Zjednoczonych. Współpracuj z frakcjami, aby przynieść pokój!]],
   weapons = {"cw_ar15", "cw_g4p_glock17"},
   command = "uninfantry",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP3 = DarkRP.createJob("MP Medic", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_medic.mdl"},
   description = [[Jesteś medykiem dla Organizacji Narodów Zjednoczonych. Utrzymaj zespół przy życiu!]],
   weapons = {"cw_g4p_ump45", "cw_g4p_glock17", "med_kit"},
   command = "unmedic",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP4 = DarkRP.createJob("MP Heavy Infantry", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Jesteście ciężką piechotą dla Organizacji Narodów Zjednoczonych. Zniszcz drzwi i zapewnij wsparcie zespołowi.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick"},
   command = "unheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP5 = DarkRP.createJob("MP Sniper", {
   color = Color(0, 0, 255, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem dla Organizacji Narodów Zjednoczonych. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"cw_g4p_m98b", "cw_g4p_glock17"},
   command = "unsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP6 = DarkRP.createJob("MP Officer", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Jesteś oficerem Organizacji Narodów Zjednoczonych. Dowodź swoimi wojskami na polu i zorganizuj taktykę obrony. Przyjmujesz zamówienia od Ambasadora i specjalisty ds. Strategicznych.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "mpofficer",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP7 = DarkRP.createJob("MP Checkpoint Guard", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Pilnujesz punktów kontrolnych ustawionych przez funkcjonariusza punktu kontrolnego.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "mpcheckpointguard",
   max = 6,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP8 = DarkRP.createJob("MP Checkpoint Officer", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Jesteś jedyną osobą, która może tworzyć punkty kontrolne. Przypisuj strażników do prowadzenia punktów kontrolnych.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "mpcheckpointofficer",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP9 = DarkRP.createJob("MP Strategic Specialist", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/pmc_1/pmc__01.mdl"},
   description = [[Specjalista strategiczny dla policji wojskowej. Opracuj plany zatrzymania wojen i przestępstw w mieście.]],
   weapons = {"cw_mr96"},
   command = "mpstrategicspecialist",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP10 = DarkRP.createJob("UN Ambassador", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/pmc_1/pmc__01.mdl"},
   description = [[Jesteś Ambasadorem Narodów Zjednoczonych. Zdecyduj, które frakcje będziecie wspierać, a które frakcje sprzeciwić się pokojowi!]],
   weapons = {},
   command = "unambassador",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- ORIGINAL U.N --
/*
TEAM_UN1 = DarkRP.createJob("UN Infantry", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[Jesteście piechotą dla Organizacji Narodów Zjednoczonych. Współpracuj z frakcjami, aby przynieść pokój!]],
   weapons = {"cw_ar15", "cw_g4p_glock17"},
   command = "uninfantry",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN2 = DarkRP.createJob("UN Hospital Defense Unit", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Jesteście jednostką obrony dla Organizacji Narodów Zjednoczonych. Chroń szpital za wszelką cenę. NIE MOŻESZ OPUSZCZAĆ OBSZARU SZPITALNEGO!]],
   weapons = {"m9k_m249lmg", "bb_glock_alt"},
   command = "undefenseunit",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN3 = DarkRP.createJob("UN Medic", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_medic.mdl"},
   description = [[Jesteś medykiem dla Organizacji Narodów Zjednoczonych. Utrzymaj zespół przy życiu!]],
   weapons = {"cw_g4p_ump45", "cw_g4p_glock17", "med_kit"},
   command = "unmedic",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN4 = DarkRP.createJob("UN Heavy Infantry", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Jesteście ciężką piechotą dla Organizacji Narodów Zjednoczonych. Zniszcz drzwi i zapewnij wsparcie zespołowi.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick"},
   command = "unheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN5 = DarkRP.createJob("UN Sniper", {
   color = Color(0, 0, 255, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[Jesteś snajperem dla Organizacji Narodów Zjednoczonych. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"m9k_intervention", "bb_glock_alt"},
   command = "unsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN6 = DarkRP.createJob("UN Lieutenant", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[Jesteś porucznikiem Organizacji Narodów Zjednoczonych. Dowodź swoimi wojskami na polu i zorganizuj taktykę obrony. Przyjmujesz zamówienia od Ambasadora.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "unlieutenant",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN7 = DarkRP.createJob("UN Ambassador", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/pmc_1/pmc__01.mdl"},
   description = [[Jesteś Ambasadorem Narodów Zjednoczonych. Zdecyduj, które frakcje będziesz wspierać i które frakcje sprzeciwiają się wprowadzeniu pokoju!]],
   weapons = {},
   command = "unambassador",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})
*/

-- PENGUIN --
TEAM_MASTER = DarkRP.createJob("Master", {
   color = Color(94, 6, 0, 255),
   model = {"models/grealms/characters/kyloren/kyloren.mdl"},
   description = [[Klasa niestandardowa pingwina. Służy jako zmiatacz i porywacz.]],
   weapons = {"cw_kk_hk416", "cw_deagle", "cw_xm1014"},
   command = "master",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- KYLE --
TEAM_ELITECYBRANCOMMANDO = DarkRP.createJob("Elite Cybran Commando", {
   color = Color(227, 8, 0, 255),
   model = {"models/blacklist/merc1.mdl",
            "models/blacklist/spy1.mdl"
            },
   description = [[Klasa niestandardowa Kyle'a. Działa jako najemnik i frakcja, której celem jest zrównoważenie władzy.]],
   weapons = {"cw_ar15", "cw_g4p_usp40", "cw_g4p_m98b", "lockpick"},
   command = "elitecybrancommando",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- BANE --
TEAM_CYBRANGUERRILLA = DarkRP.createJob("Cybran Guerrilla", {
   color = Color(227, 8, 0, 255),
   model = {"models/blacklist/merc1.mdl",
            "models/blacklist/spy1.mdl"
            },
   description = [[Klasa niestandardowa Kyle'a. Działa jako najemnik i frakcja, której celem jest zrównoważenie władzy....]],
   weapons = {"cw_g4p_fn_fal", "cw_deagle", "cw_kriss_5_vector", "m9k_damascus"},
   command = "cybranguerrilla",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- STARK --
TEAM_AVENGER = DarkRP.createJob("Avenger", {
   color = Color(189, 189, 189, 255),
   model = {"models/player/slow/tk/ironman/slow_v3.mdl"},
   description = [[Klasa niestandardowa Starka. Działa jako najemnik.]],
   weapons = {"cw_g4p_an94", "cw_g4p_fiveseven", "cw_kriss_5_vector", "lockpick"},
   command = "avenger",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- SQUIDBOW --
TEAM_SQUIDBOW = DarkRP.createJob("GHOST", {
   color = Color(0, 181, 228, 255),
   model = {"models/codmw2/codmw2m.mdl"},
   description = [[Najemnik]],
   weapons = {"cw_g4p_m16a2", "cw_deagle", "cw_xm1014", "lockpick", "keypad_cracker"},
   command = "ghost",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- CHAIR --
TEAM_CHAIR = DarkRP.createJob("Wasteland Rebel", {
   color = Color(255, 128, 0, 255),
   model = {"models/fallout_nv/nikout/lonesomeroad/riotsoldier.mdl"},
   description = [[Najemnik]],
   weapons = {"cw_ak74", "cw_deagle"},
   command = "wastelandrebel",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(50) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- BANANA --
TEAM_BANANA = DarkRP.createJob("Imperial Commando", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/star wars the force awakens/spartanmark6/first order trooper/ep7_stormtrooper.mdl"},
   description = [[Najemnik]],
   weapons = {"cw_ak74", "cw_deagle", "cw_g4p_m98b", "med_kit"},
   command = "imperialcommando",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(75) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- CJB / FLIC --
TEAM_CJB = DarkRP.createJob("Ghost", {
   color = Color(253, 52, 0, 255),
   model = {"models/player/pd2_hoxton_p.mdl"},
   description = [[Niestandardowa klasa Flica. Działa jako padlinożerca.]],
   weapons = {"cw_g4p_m16a4", "cw_deagle", "m9k_damascus", "cw_g4p_m98b"},
   command = "cjbghost",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(75) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- TABETIC --
TEAM_TABETIC = DarkRP.createJob("Reaper", {
   color = Color(198, 203, 42, 255),
   model = {"models/grim.mdl"},
   description = [[Klasa niestandardowa Tabetic. Działa jako najemnik.]],
   weapons = {"cw_g4p_fn_fal", "cw_deagle"},
   command = "reaper",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(50) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

/*
-- SQUIDBOW SECOND CC --
TEAM_TABETIC = DarkRP.createJob("BAYMAX", {
   color = Color(255, 0, 0, 255),
   model = {"models/grim.mdl"},
   description = [[Klasa niestandardowa Squid. Działa jako najemnik.]],
   weapons = {"cw_g4p_fn_fal", "cw_deagle"},
   command = "baymax",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})
*/

-- INTERESTINGBUTSTUPID --
TEAM_TABETIC = DarkRP.createJob("Anti-Raider", {
   color = Color(228, 8, 8, 255),
   model = {"models/grim.mdl"},
   description = [[klasa niestandardowa ciekawych butów. Ta praca będzie klasą do wynajęcia, która koncentruje się na niszczeniu drużyn rajdowych spoza bazy drużyny broniącej się.]],
   weapons = {"cw_ar15", "cw_g4p_mp412_rex", "cw_kriss_5_vector", "lockpick", "keypad_cracker"},
   command = "antiraider",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- .STREET --
TEAM_TABETIC = DarkRP.createJob("Brute", {
   color = Color(0, 0, 0, 255),
   model = {"models/codmw2/codmw2m.mdl"},
   description = [[Klasa niestandardowa .Street. Działa jako najemnik.]],
   weapons = {"cw_ak74", "cw_deagle"},
   command = "brute",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(50) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})


--[[// U.S BREACHER
// models/codmw2/codmw2.mdl

// U.S COLONEL
// models/codmw2/codmw2he.mdl

// U.S | LIEUTENANT W/ MORE GEAR
// models/codmw2/codmw2hexe.mdl

// GHOST
// models/codmw2/codmw2m.mdl

// U.S LIEUTENANT
// models/codmw2/t_codm.mdl]]

-- Compatibility for when default teams are disabled

TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1


/*
--------------------------------------------------------
HOW TO MAKE A DOOR GROUP
--------------------------------------------------------
AddDoorGroup("NAME OF THE GROUP HERE, you see this when looking at a door", Team1, Team2, team3, team4, etc.)


The default door groups, can also be used as examples:
*/
AddDoorGroup("United States", TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8, TEAM_US9)
--AddDoorGroup("Russia", TEAM_RU1, TEAM_RU2, TEAM_RU3, TEAM_RU4, TEAM_RU5, TEAM_RU6, TEAM_RU7, TEAM_RU8, TEAM_RU9)
--AddDoorGroup("New World Order", TEAM_NWO1, TEAM_NWO2, TEAM_NWO3, TEAM_NWO4, TEAM_NWO5, TEAM_NWO6, TEAM_NWO7, TEAM_NWO8, TEAM_NWO9)
AddDoorGroup("Germany", TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8, TEAM_DE9)
AddDoorGroup("United Nations", TEAM_UN1, TEAM_UN2, TEAM_UN3, TEAM_UN4, TEAM_UN5, TEAM_UN6, TEAM_UN7)
AddDoorGroup("China", TEAM_CN1, TEAM_CN2, TEAM_CN3, TEAM_CN4, TEAM_CN5, TEAM_CN6, TEAM_CN7, TEAM_CN8, TEAM_CN9)
--AddDoorGroup("Military Police", TEAM_MP1, TEAM_MP2, TEAM_MP3, TEAM_MP4, TEAM_MP5, TEAM_MP6, TEAM_MP7)


/*
--------------------------------------------------------
HOW TO MAKE AN AGENDA
--------------------------------------------------------
DarkRP.createAgenda(Title of the agenda, Manager (who edits it), Listeners (the ones who just see and follow the agenda))
Its possible to have multiple managers. In that case you have to put all the managers in '{}' (see Police agenda)

The default agendas, can also be used as examples:
*/
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})
DarkRP.createAgenda("United States", {TEAM_US9}, {TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8})
DarkRP.createAgenda("Germany", {TEAM_DE9}, {TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8})
DarkRP.createAgenda("China", {TEAM_CN9}, {TEAM_CN1, TEAM_CN2, TEAM_CN3, TEAM_CN4, TEAM_CN5, TEAM_CN6, TEAM_CN7, TEAM_CN8})
--DarkRP.createAgenda("Military Police", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})



/*
---------------------------------------------------------------------------
HOW TO MAKE A GROUP CHAT
---------------------------------------------------------------------------
Pick one!
DarkRP.createGroupChat(List of team variables separated by comma)

or

DarkRP.createGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This one is for people who know how to script Lua.

*/
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8, TEAM_US9)

--DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
--DarkRP.createGroupChat(TEAM_RU1, TEAM_RU2, TEAM_RU3, TEAM_RU4, TEAM_RU5, TEAM_RU6, TEAM_RU7, TEAM_RU8, TEAM_RU9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_NWO1, TEAM_NWO2, TEAM_NWO3, TEAM_NWO4, TEAM_NWO5, TEAM_NWO6, TEAM_NWO7, TEAM_NWO8, TEAM_NWO9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8, TEAM_DE9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_CELL1, TEAM_CELL2, TEAM_CELL3, TEAM_CELL4, TEAM_CELL5, TEAM_CELL6, TEAM_CELL7, TEAM_CELL8)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_UN1, TEAM_UN2, TEAM_UN3, TEAM_UN4, TEAM_UN5, TEAM_UN6, TEAM_UN7)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_T1, TEAM_T2, TEAM_T3)
/*---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN

/*---------------------------------------------------------------------------
Default categories
---------------------------------------------------------------------------*/

DarkRP.createCategory{
   name = "Administration",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 0, 0, 255),
   canSee = fp{fn.Id, false},
   sortOrder = 1,
}

DarkRP.createCategory{
   name = "United States",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 150, 255, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 3,
}
/*
DarkRP.createCategory{
   name = "New World Order",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 20, 84, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 4,
}
*/
/*
DarkRP.createCategory{
   name = "Russia",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 0, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 5,
}
*/

DarkRP.createCategory{
   name = "Germany",
   categorises = "jobs",
   startExpanded = false,
   color = Color(32, 32, 32, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 6,
}

DarkRP.createCategory{
   name = "U.N Military Police",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 0, 255, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 7,
}

DarkRP.createCategory{
   name = "XOF Military Company",
   categorises = "jobs",
   startExpanded = false,
   color = Color(107, 101, 43, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 8,
}

DarkRP.createCategory{
   name = "Terrorists",
   categorises = "jobs",
   startExpanded = false,
   color = Color(102, 102, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 9,
}

DarkRP.createCategory{
   name = "Custom Classes",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 255, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 10,
}

DarkRP.createCategory{
   name = "China",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 56, 25, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 11,
}

DarkRP.createCategory{
   name = "Anarchists",
   categorises = "jobs",
   startExpanded = false,
   color = Color(120, 0, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 12,
}

DarkRP.createCategory{
   name = "Other",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 107, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 255,
}
