-- Twórcy Prac: Zabójca997, Mr.Jeżyk.
-- Prace obejmują prawa autorkie z zmiana prac.
-- Prace są własnością serwera: ExtremeOnly, GameResidance.
local GAMEMODE = GAMEMODE or GM
/*--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------*/
TEAM_AOD = DarkRP.createJob("Wybieranie strony", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/police.mdl"},
   description = [[Wybierz swoja prace!]],
   weapons = {},
   command = "aod",
   max = 0,
   salary = 0,
   admin = 1,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Administration",
})

TEAM_AOD = DarkRP.createJob("Developer", {
   color = Color(255, 255, 0, 255),
   model = {"models/Combine_Super_Soldier.mdl"},
   description = [[Klasa rozwijana do użytku wyłącznie przez programistów.]],
   weapons = {},
   command = "dev",
   max = 0,
   salary = 0,
   admin = 1,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Administration",
   customCheck = function(ply) return ply:SteamID() == "STEAM_0:0:53440724" end,
})

TEAM_SCAVENGER = AddExtraTeam("Scavenger", {
    color = Color(20, 150, 20, 255),
    model = "models/player/arctic.mdl",
    description = [[Wyjdź i przeszukaj bazy Cilian i zabierz ich rzeczy.]],
    weapons = {"weapon_fists", "lockpick", "keypad_cracker"},
    command = "scavenger",
    max = 5,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_RAIDER = AddExtraTeam("Raider", {
   color = Color(20, 150, 20, 255),
    model = "models/player/legion/3e_soldier.mdl",
    description = [[Zaawansowany śmieciarz.]],
    weapons = {"weapon_fists", "lockpick", "keypad_cracker", "m9k_colt1911"},
    command = "raider",
    max = 2,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians",
     customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_RAIDER = AddExtraTeam("Abductor", {
   color = Color(20, 150, 20, 255),
    model = "models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl",
    description = [[Porywacze porywają (porywają) ludzi i trzymają ich za okup. Maksymalny okup to 100 000 $.]],
    weapons = {"weapon_cuff_elastic", "m9k_spas12"},
    command = "abductor",
    max = 1,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_LGUN = AddExtraTeam("Light Arms Dealer", {
    color = Color(20, 150, 20, 255),
    model = "models/player/kgb.mdl",
    description = [[Neutralna partia wszystkich wojen. Dostarcza broń żołnierzom.]],
    weapons = {"m9k_spas12", "m9k_usas", "m9k_mossberg590", "m9k_model627", "m9k_coltpython", "m9k_mp5sd", "m9k_aw50", "m9k_magpulpdr", "m9k_svu", "m9k_ares_shrike", "m9k_fg42", "m9k_acr"},
    command = "lightarmsdealer",
    max = 2,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_US1 = DarkRP.createJob("US Rekrut", {
   color = Color(0, 128, 255, 255),
   model = {"models/ninja/bf3/player/us_nick.mdl"},
   description = [[Jesteś jednostką piechoty dla armii Stanów Zjednoczonych. Postępuj zgodnie z poleceniami przełożonego i poprowadź USA do zwycięstwa!]],
   weapons = {"m9k_acr", "m9k_deagle"},
   command = "usinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "United States",
})

TEAM_US2 = DarkRP.createJob("US Recon Unit", {
   color = Color(0, 128, 255, 255),
   model = {"models/ninja/bf3/player/us_test_shemagh_alt.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla armii Stanów Zjednoczonych. Twoim zadaniem jest zebranie informacji o jednostkach wroga]],
   weapons = {"m9k_deagle", "m9k_m416"},
   command = "usrecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US3 = DarkRP.createJob("US Heavy Infantry", {
   color = Color(0, 128, 255, 255),
   model = {"models/usmopp/soldier_mopp.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla armii Stanów Zjednoczonych. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"m9k_m249lmg", "m9k_scoped_taurus"},
   command = "usheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US4 = DarkRP.createJob("US Sniper", {
   color = Color(0, 128, 255, 255),
   model = {"models/mw2/skin_09/mw2_soldier_06.mdl", "models/mw2/skin_12/mw2_soldier_06.mdl"},
   description = [[Jesteś snajperem dla armii Stanów Zjednoczonych. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką zwiadowczą, aby uzyskać maksymalną biegłość!]],
   weapons = {"m9k_aw50", "weapon_vj_smg1"},
   command = "ussniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US5 = DarkRP.createJob("US Support Unit", {
   color = Color(0, 128, 255, 255),
   model = {"models/mw2/skin_09/mw2_soldier_02.mdl"},
   description = [[Jesteś jednostką wsparcia dla armii Stanów Zjednoczonych! Połóżcie osłonę ognia i stłumcie wroga!]],
   weapons = {"m9k_m16a4_acog", "m9k_deagle"},
   command = "ussupportunit",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US6 = DarkRP.createJob("US Medic", {
   color = Color(0, 128, 255, 255),
   model = {"models/arachnit/hdtf/characters/soldier/soldier_player.mdl"},
   description = [[Jesteś medykiem dla armii Stanów Zjednoczonych. Twoim zadaniem jest uleczyć swój zespół i utrzymać ich przy życiu!]],
   weapons = {"m9k_knife", "v92_hl2_medkit"},
   command = "usmedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US7 = DarkRP.createJob("US Officer", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/sanic/marinedp.mdl", "models/player/sanic/marinewp.mdl", "models/player/sanic/marinewv2p.mdl", "models/player/sanic/marinedv2.mdl"},
   description = [[Jesteś oficerem armii Stanów Zjednoczonych. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony i innych działań. Przyjmujesz rozkazy od dowódcy.]],
   weapons = {"m9k_thompson", "m9k_model627"},
   command = "usofficer",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US8 = DarkRP.createJob("US Commander", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/price_phoenix.mdl"},
   description = [[Jesteś dowódcą armii Stanów Zjednoczonych. Przyjmij rozkazy od generała armii i dowodź swoimi żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"m9k_scar", "m9k_sig_p229r"},
   command = "uscommander",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US9 = DarkRP.createJob("US General of the Army", {
   color = Color(0, 128, 255, 255),
   model = {"models/bloocobalt/science/jnavy_09.mdl"},
   description = [[Jesteś generałem armii Stanów Zjednoczonych. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co masz robić, a pułkownik sprawdzi.]],
   weapons = {"m9k_an94", "m9k_glock"},
   command = "usgota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
   customCheck = function(ply) return CLIENT or
        table.HasValue({"STEAM_0:1:174545413"}, ply:SteamID())
    end,
    CustomCheckFailMsg = "Tylko Kamo może być generałem",
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "The U.S General of the Army has been killed!")
      else
         DarkRP.notifyAll(0, 4, "The U.S General of the Army has died!")
      end
   end
})                                                                                                                   

TEAM_US10 = DarkRP.createJob("US Special Forces", {
   color = Color(0, 128, 255, 255),
   model = {"models/player/bms_blackops.mdl"},
   description = [[Jesteś „drużyną” jednoosobowych sił specjalnych. Przyjmujesz rozkazy bezpośrednio od generała armii.]],
   weapons = {"m9k_matador", "m9k_deagle"},
   command = "usspecialforces",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

/*
TEAM_RU1 = DarkRP.createJob("RU Infantry", {
   level = 5,
   color = Color(228, 0, 0, 255),
   model = {"models/russianbear2345/bf3/engie_ru.mdl"},
   description = [[Jesteś jednostką piechoty dla armii rosyjskiej. Postępuj zgodnie z rozkazami przełożonego i poprowadź Rosję do zwycięstwa!]],
   weapons = {"m9k_ak74", "m9k_hk45"},
   command = "ruinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU2 = DarkRP.createJob("RU Recon Unit", {
   level = 1,
   color = Color(228, 0, 0, 255),
   model = {"models/russianbear2345/bf3/engie_ru.mdl"},
   description = [[Jesteś jednostką rozpoznawczą dla rosyjskiej armii. Twoim zadaniem jest zebranie informacji o jednostkach wroga.]],
   weapons = {"util_binoculars", "m9k_hk45"},
   command = "rurecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU3 = DarkRP.createJob("RU Heavy Infantry", {
   level = 20,
   color = Color(228, 0, 0, 255),
   model = {"models/russianbear2345/bf3/alternate/medic_ru.mdl"},
   description = [[Jesteś ciężką jednostką piechoty dla rosyjskiej armii. Jesteś blisko i osobisty i jako pierwszy wejdziesz do bazy podczas najazdu.]],
   weapons = {"m9k_remington870", "m9k_hk45", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "ruheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU4 = DarkRP.createJob("RU Sniper", {
   level = 30,
   color = Color(228, 0, 0, 255),
   model = {"models/russianbear2345/bf3/medic_ru.mdl"},
   description = [[Jesteś snajperem dla armii rosyjskiej. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"m9k_dragunov", "m9k_hk45"},
   command = "rusniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU5 = DarkRP.createJob("RU Light Machine Gunner", {
   level = 50,
   color = Color(228, 0, 0, 255),
   model = {"models/russianbear2345/bf3/alternate/support_ru.mdl"},
   description = [[Jesteś lekkim strzelcem dla armii rosyjskiej. Twoim zadaniem jest obrona bazy. NIE DOŁĄCZAJ DO RAIDÓW. JESTEŚ JEDNOSTKĄ OBRONNĄ, A NIE JEDNOSTKĄ OBRONNĄ!]],
   weapons = {"m9k_pkm", "m9k_hk45"},
   command = "rulightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU6 = DarkRP.createJob("RU Medic", {
   level = 15,
   color = Color(228, 0, 0, 255),
   model = {"models/russianbear2345/bf3/support_ru.mdl"},
   description = [[Jesteś medykiem dla rosyjskiej armii. Twoim zadaniem jest uleczyć swój zespół i utrzymać ich przy życiu!]],
   weapons = {"weapon_medkit", "m9k_an94", "m9k_hk45"},
   command = "rumedic",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU7 = DarkRP.createJob("RU Lieutenant", {
   level = 50,
   color = Color(228, 0, 0, 255),
   model = {"models/amisaddai/bf3/engineer2.mdl"},
   description = [[Jesteś porucznikiem armii rosyjskiej. Twoim zadaniem jest zebranie drużyny członków drużyny do patrolowania, nalotów, obrony, itp. Przyjmujesz rozkazy od pułkownika.]],
   weapons = {"m9k_amd65", "m9k_hk45"},
   command = "rulieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU8 = DarkRP.createJob("RU Colonel", {
   level = 75,
   color = Color(228, 0, 0, 255),
   model = {"models/player/apsci_male_09.mdl"},
   description = [[Jesteś pułkownikiem armii rosyjskiej. Przyjmij rozkazy od generała armii i dowodź żołnierzami tak, jak chcesz, aby wykonać misję.]],
   weapons = {"m9k_ak74", "m9k_hk45"},
   command = "rucolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_RU9 = DarkRP.createJob("RU General of the Army", {
   color = Color(228, 0, 0, 255),
   model = {"models/player/apsci_male_04.mdl"},
   description = [[Jesteś rosyjskim generałem armii. Wypowiadacie wojny, akceptujecie traktaty pokojowe, sojusze i tak dalej. Rozkazujesz pułkownikowi, co ma robić, i pułkownik sprawi, że będzie to zrobione.]],
   weapons = {},
   command = "rugota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
   PlayerDeath = function(ply, weapon, killer)
      ply:teamBan()
      ply:changeTeam(GAMEMODE.DefaultTeam, true)
      if killer:IsPlayer() then
         DarkRP.notifyAll(0, 4, "Rosyjski generał armii został zabity!")
      else
         DarkRP.notifyAll(0, 4, "Rosyjski generał armii zmarł!")
      end
   end
})
*/

/*

/*
TEAM_T1 = DarkRP.createJob("Terrorist", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/gru.mdl"},
   description = [[Jesteś standardowym terrorystą. Przyjmij rozkazy od swojego lidera. PAMIĘTAJ, ŻE TYLKO 30 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {},
   command = "terrorist",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "Terrorists",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_T2 = DarkRP.createJob("Terrorist Leader", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/ocelot.mdl"},
   description = [[Jesteś przywódcą terrorystów. Poinformuj innych terrorystów o swoich planach na maksymalny chaos! PAMIĘTAJ, ŻE TYLKO 30 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {},
   command = "terroristleader",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Terrorists",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end
})

TEAM_T3 = DarkRP.createJob("Suicide Bomber", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_bomber.mdl"},
   description = [[Jesteś zamachowcem-samobójcą! Wysadź się w powietrze, aby wywołać chaos! PAMIĘTAJ, ŻE TYLKO 15 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {"m9k_suicide_bomb"},
   command = "suicidebomber",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 3,
   category = "Terrorists",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end
})
*/

TEAM_A1 = DarkRP.createJob("Anarchist", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/bobert/aodeadshot.mdl"},
   description = [[Jesteś zwykłym anarchistą. Przyjmij rozkazy od swojego przywódcy Anarchii i zlikwiduj wszystkie formy rządów!]],
   weapons = {},
   command = "anarchist",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "Anarchists",
   customCheck = function(ply)
        return ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_A2 = DarkRP.createJob("Anarchy", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/bobert/aoa.mdl"},
   description = [[Jesteś liderem anarchistów. Powiedz innym anarchistom, że planujesz obalić wszystkie formy rządzenia!]],
   weapons = {},
   command = "anarchy",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Anarchists",
   customCheck = function(ply)
        return ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

/*
TEAM_A3 = DarkRP.createJob("Anarchist Bomber", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_bomber.mdl"},
   description = [[Jesteś zamachowcem-samobójcą! Wysadź się w powietrze, aby wywołać chaos! PAMIĘTAJ, ŻE TYLKO 15 MINUT MOŻESZ ZROBIĆ TERRORYSTYCZNY ATAK!]],
   weapons = {"m9k_suicide_bomb"},
   command = "anarchistbomber",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 3,
   category = "Anarchists ",
   customCheck = function(ply)
        return ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})
*/

TEAM_MP1 = DarkRP.createJob("MP Soldier", {
   color = Color(0, 0, 255, 255),
   model = {"models/sentry/mp01.mdl"},
   description = [[Jesteście piechotą dla Organizacji Narodów Zjednoczonych. Współpracuj z frakcjami, aby przynieść pokój!]],
   weapons = {"cw_ar15", "cw_g4p_glock17"},
   command = "uninfantry",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP3 = DarkRP.createJob("MP Medic", {
   color = Color(0, 0, 255, 255),
   model = {"models/sentry/mp07.mdl"},
   description = [[Jesteś medykiem dla Organizacji Narodów Zjednoczonych. Utrzymaj zespół przy życiu!]],
   weapons = {"cw_g4p_ump45", "cw_g4p_glock17", "med_kit"},
   command = "unmedic",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP4 = DarkRP.createJob("MP Heavy Infantry", {
   color = Color(0, 0, 255, 255),
   model = {"models/mw2/skin_09/mw2_soldier_03.mdl"},
   description = [[Jesteście ciężką piechotą dla Organizacji Narodów Zjednoczonych. Zniszcz drzwi i zapewnij wsparcie zespołowi.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick"},
   command = "unheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP5 = DarkRP.createJob("MP Sniper", {
   color = Color(0, 0, 255, 255),
   model = {"models/mw2/skin_05/mw2_soldier_06.mdl"},
   description = [[Jesteś snajperem dla Organizacji Narodów Zjednoczonych. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"cw_g4p_m98b", "cw_g4p_glock17"},
   command = "unsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP6 = DarkRP.createJob("MP Officer", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/police/custom_rmp/custom_rmp.mdl"},
   description = [[Jesteś oficerem Organizacji Narodów Zjednoczonych. Dowodź swoimi wojskami na polu i zorganizuj taktykę obrony. Przyjmujesz zamówienia od Ambasadora i specjalisty ds. Strategicznych.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "mpofficer",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP7 = DarkRP.createJob("MP Checkpoint Guard", {
   color = Color(0, 0, 255, 255),
   model = {"models/mw2/skin_04/mw2_soldier_01.mdl"},
   description = [[Pilnujesz punktów kontrolnych ustawionych przez funkcjonariusza punktu kontrolnego.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "mpcheckpointguard",
   max = 6,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP8 = DarkRP.createJob("MP Checkpoint Officer", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/police/custom_rmp/custom_rmp.mdl"},
   description = [[Jesteś jedyną osobą, która może tworzyć punkty kontrolne. Przypisuj strażników do prowadzenia punktów kontrolnych.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "mpcheckpointofficer",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP9 = DarkRP.createJob("MP Strategic Specialist", {
   color = Color(0, 0, 255, 255),
   model = {"models/player/frosty/policia_argentino11.mdl"},
   description = [[Specjalista strategiczny dla policji wojskowej. Opracuj plany zatrzymania wojen i przestępstw w mieście.]],
   weapons = {"cw_mr96"},
   command = "mpstrategicspecialist",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_MP10 = DarkRP.createJob("UN Ambassador", {
   color = Color(0, 0, 255, 255),
   model = {"models/t37/player/navalny/navalny.mdl"},
   description = [[Jesteś Ambasadorem Narodów Zjednoczonych. Zdecyduj, które frakcje będziecie wspierać, a które frakcje sprzeciwić się pokojowi!]],
   weapons = {},
   command = "unambassador",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "U.N Military Police",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- ORIGINAL U.N --
/*
TEAM_UN1 = DarkRP.createJob("UN Infantry", {
   color = Color(0, 0, 255, 255),
   model = {"models/brinks/security/guard_brinks_4.mdl"},
   description = [[Jesteście piechotą dla Organizacji Narodów Zjednoczonych. Współpracuj z frakcjami, aby przynieść pokój!]],
   weapons = {"cw_ar15", "cw_g4p_glock17"},
   command = "uninfantry",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN2 = DarkRP.createJob("UN Hospital Defense Unit", {
   color = Color(0, 0, 255, 255),
   model = {"models/brinks/security/guard_brinks_6.mdl"},
   description = [[Jesteście jednostką obrony dla Organizacji Narodów Zjednoczonych. Chroń szpital za wszelką cenę. NIE MOŻESZ OPUSZCZAĆ OBSZARU SZPITALNEGO!]],
   weapons = {"m9k_m249lmg", "bb_glock_alt"},
   command = "undefenseunit",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN3 = DarkRP.createJob("UN Medic", {
   color = Color(0, 0, 255, 255),
   model = {"models/brinks/security/guard_brinks_6.mdl"},
   description = [[Jesteś medykiem dla Organizacji Narodów Zjednoczonych. Utrzymaj zespół przy życiu!]],
   weapons = {"cw_g4p_ump45", "cw_g4p_glock17", "med_kit"},
   command = "unmedic",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN4 = DarkRP.createJob("UN Heavy Infantry", {
   color = Color(0, 0, 255, 255),
   model = {"models/mw2/skin_03/mw2_soldier_02.mdl"},
   description = [[Jesteście ciężką piechotą dla Organizacji Narodów Zjednoczonych. Zniszcz drzwi i zapewnij wsparcie zespołowi.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick"},
   command = "unheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN5 = DarkRP.createJob("UN Sniper", {
   color = Color(0, 0, 255, 255),
   model = {"models/mw2/skin_03/mw2_soldier_06.mdl"},
   description = [[Jesteś snajperem dla Organizacji Narodów Zjednoczonych. Wykonuj rozkazy oficera i wykorzystaj swoje umiejętności strzelania, aby pokonać wrogów! Współpracuj z jednostką rozpoznającą, aby uzyskać maksymalną biegłość!]],
   weapons = {"m9k_intervention", "bb_glock_alt"},
   command = "unsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN6 = DarkRP.createJob("UN Lieutenant", {
   color = Color(0, 0, 255, 255),
   model = {"models/brinks/security/guard_brinks_1.mdl"},
   description = [[Jesteś porucznikiem Organizacji Narodów Zjednoczonych. Dowodź swoimi wojskami na polu i zorganizuj taktykę obrony. Przyjmujesz zamówienia od Ambasadora.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "unlieutenant",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_UN7 = DarkRP.createJob("UN Ambassador", {
   color = Color(0, 0, 255, 255),
   model = {"models/players/mj_re6_formalchris.mdl"},
   description = [[Jesteś Ambasadorem Narodów Zjednoczonych. Zdecyduj, które frakcje będziesz wspierać i które frakcje sprzeciwiają się wprowadzeniu pokoju!]],
   weapons = {},
   command = "unambassador",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})
*/

TEAM_SQUIDBOW = DarkRP.createJob("GHOST", {
   color = Color(0, 181, 228, 255),
   model = {"models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl"},
   description = [[Najemnik]],
   weapons = {"cw_g4p_m16a2", "cw_deagle", "cw_xm1014", "lockpick", "keypad_cracker"},
   command = "ghost",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_CJB = DarkRP.createJob("Ghost", {
   color = Color(253, 52, 0, 255),
   model = {"models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl"},
   description = [[Niestandardowa klasa Flica. Działa jako padlinożerca.]],
   weapons = {"cw_g4p_m16a4", "cw_deagle", "m9k_damascus", "cw_g4p_m98b"},
   command = "cjbghost",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(75) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

TEAM_TABETIC = DarkRP.createJob("Reaper", {
   color = Color(198, 203, 42, 255),
   model = {"models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl"},
   description = [[Klasa niestandardowa Tabetic. Działa jako najemnik.]],
   weapons = {"cw_g4p_fn_fal", "cw_deagle"},
   command = "reaper",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(50) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

/*
-- SQUIDBOW SECOND CC --
TEAM_TABETIC = DarkRP.createJob("BAYMAX", {
   color = Color(255, 0, 0, 255),
   model = {"models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl"},
   description = [[Klasa niestandardowa Squid. Działa jako najemnik.]],
   weapons = {"cw_g4p_fn_fal", "cw_deagle"},
   command = "baymax",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})
*/

-- INTERESTINGBUTSTUPID --
TEAM_TABETIC = DarkRP.createJob("Anti-Raider", {
   color = Color(228, 8, 8, 255),
   model = {"models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl"},
   description = [[klasa niestandardowa ciekawych butów. Ta praca będzie klasą do wynajęcia, która koncentruje się na niszczeniu drużyn rajdowych spoza bazy drużyny broniącej się.]],
   weapons = {"cw_ar15", "cw_g4p_mp412_rex", "cw_kriss_5_vector", "lockpick", "keypad_cracker"},
   command = "antiraider",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(100) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})

-- .STREET --
TEAM_TABETIC = DarkRP.createJob("Brute", {
   color = Color(0, 0, 0, 255),
   model = {"models/arachnit/csgooldphoenix/tm_phoenix_variant_a_ragdoll.mdl"},
   description = [[Klasa niestandardowa .Street. Działa jako najemnik.]],
   weapons = {"cw_ak74", "cw_deagle"},
   command = "brute",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   category = "Custom Classes",
   PlayerSpawn =  function(ply) ply:SetArmor(50) ply:SetAmmo(600 , "ar2") end,
   customCheck = function(ply) return
        table.HasValue({"xD"}, ply:SteamID())
    end,
})


--[[// U.S BREACHER
// models/codmw2/codmw2.mdl
// U.S COLONEL
// models/codmw2/codmw2he.mdl
// U.S | LIEUTENANT W/ MORE GEAR
// models/codmw2/codmw2hexe.mdl
// GHOST
// models/codmw2/codmw2m.mdl
// U.S LIEUTENANT
// models/codmw2/t_codm.mdl]]

-- Compatibility for when default teams are disabled

TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1


/*
--------------------------------------------------------
HOW TO MAKE A DOOR GROUP
--------------------------------------------------------
AddDoorGroup("NAME OF THE GROUP HERE, you see this when looking at a door", Team1, Team2, team3, team4, etc.)


The default door groups, can also be used as examples:
*/
AddDoorGroup("United States", TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8, TEAM_US9)
--AddDoorGroup("Russia", TEAM_RU1, TEAM_RU2, TEAM_RU3, TEAM_RU4, TEAM_RU5, TEAM_RU6, TEAM_RU7, TEAM_RU8, TEAM_RU9)
--AddDoorGroup("New World Order", TEAM_NWO1, TEAM_NWO2, TEAM_NWO3, TEAM_NWO4, TEAM_NWO5, TEAM_NWO6, TEAM_NWO7, TEAM_NWO8, TEAM_NWO9)
AddDoorGroup("Germany", TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8, TEAM_DE9)
AddDoorGroup("United Nations", TEAM_UN1, TEAM_UN2, TEAM_UN3, TEAM_UN4, TEAM_UN5, TEAM_UN6, TEAM_UN7)
AddDoorGroup("China", TEAM_CN1, TEAM_CN2, TEAM_CN3, TEAM_CN4, TEAM_CN5, TEAM_CN6, TEAM_CN7, TEAM_CN8, TEAM_CN9)
--AddDoorGroup("Military Police", TEAM_MP1, TEAM_MP2, TEAM_MP3, TEAM_MP4, TEAM_MP5, TEAM_MP6, TEAM_MP7)


/*
--------------------------------------------------------
HOW TO MAKE AN AGENDA
--------------------------------------------------------
DarkRP.createAgenda(Title of the agenda, Manager (who edits it), Listeners (the ones who just see and follow the agenda))
Its possible to have multiple managers. In that case you have to put all the managers in '{}' (see Police agenda)

The default agendas, can also be used as examples:
*/
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})
DarkRP.createAgenda("United States", {TEAM_US9}, {TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8})
DarkRP.createAgenda("Germany", {TEAM_DE9}, {TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8})
DarkRP.createAgenda("China", {TEAM_CN9}, {TEAM_CN1, TEAM_CN2, TEAM_CN3, TEAM_CN4, TEAM_CN5, TEAM_CN6, TEAM_CN7, TEAM_CN8})
--DarkRP.createAgenda("Military Police", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})



/*
---------------------------------------------------------------------------
HOW TO MAKE A GROUP CHAT
---------------------------------------------------------------------------
Pick one!
DarkRP.createGroupChat(List of team variables separated by comma)

or

DarkRP.createGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This one is for people who know how to script Lua.

*/
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8, TEAM_US9)

--DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
--DarkRP.createGroupChat(TEAM_RU1, TEAM_RU2, TEAM_RU3, TEAM_RU4, TEAM_RU5, TEAM_RU6, TEAM_RU7, TEAM_RU8, TEAM_RU9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_NWO1, TEAM_NWO2, TEAM_NWO3, TEAM_NWO4, TEAM_NWO5, TEAM_NWO6, TEAM_NWO7, TEAM_NWO8, TEAM_NWO9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8, TEAM_DE9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_CELL1, TEAM_CELL2, TEAM_CELL3, TEAM_CELL4, TEAM_CELL5, TEAM_CELL6, TEAM_CELL7, TEAM_CELL8)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_UN1, TEAM_UN2, TEAM_UN3, TEAM_UN4, TEAM_UN5, TEAM_UN6, TEAM_UN7)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_T1, TEAM_T2, TEAM_T3)
/*---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN

/*---------------------------------------------------------------------------
Default categories
---------------------------------------------------------------------------*/

DarkRP.createCategory{
   name = "Administration",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 0, 0, 255),
   canSee = fp{fn.Id, false},
   sortOrder = 1,
}

DarkRP.createCategory{
   name = "United States",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 150, 255, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 3,
}
/*
DarkRP.createCategory{
   name = "New World Order",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 20, 84, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 4,
}
*/
/*
DarkRP.createCategory{
   name = "Russia",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 0, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 5,
}
*/

DarkRP.createCategory{
   name = "Germany",
   categorises = "jobs",
   startExpanded = false,
   color = Color(32, 32, 32, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 6,
}

DarkRP.createCategory{
   name = "U.N Military Police",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 0, 255, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 7,
}

DarkRP.createCategory{
   name = "XOF Military Company",
   categorises = "jobs",
   startExpanded = false,
   color = Color(107, 101, 43, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 8,
}

DarkRP.createCategory{
   name = "Terrorists",
   categorises = "jobs",
   startExpanded = false,
   color = Color(102, 102, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 9,
}

DarkRP.createCategory{
   name = "Custom Classes",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 255, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 10,
}

DarkRP.createCategory{
   name = "China",
   categorises = "jobs",
   startExpanded = false,
   color = Color(255, 56, 25, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 11,
}

DarkRP.createCategory{
   name = "Anarchists",
   categorises = "jobs",
   startExpanded = false,
   color = Color(120, 0, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 12,
}

DarkRP.createCategory{
   name = "Other",
   categorises = "jobs",
   startExpanded = false,
   color = Color(0, 107, 0, 255),
   canSee = fp{fn.Id, true},
   sortOrder = 255,
}
